# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'visual_inspection_gui_HR.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1352, 891)
        MainWindow.setLayoutDirection(QtCore.Qt.RightToLeft)
        MainWindow.setDockNestingEnabled(True)
        MainWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMaximumSize(QtCore.QSize(1510, 862))
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setAutoFillBackground(True)
        self.centralwidget.setObjectName("centralwidget")
        self.gridlayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridlayout.setContentsMargins(1, 1, 1, 1)
        self.gridlayout.setSpacing(1)
        self.gridlayout.setObjectName("gridlayout")
        self.frame_6 = QtWidgets.QFrame(self.centralwidget)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.coil_coordinate_input = QtWidgets.QLineEdit(self.frame_6)
        self.coil_coordinate_input.setGeometry(QtCore.QRect(140, 0, 161, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.coil_coordinate_input.setFont(font)
        self.coil_coordinate_input.setObjectName("coil_coordinate_input")
        self.coilcoordinateslabel = QtWidgets.QLabel(self.frame_6)
        self.coilcoordinateslabel.setGeometry(QtCore.QRect(20, 0, 124, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.coilcoordinateslabel.setFont(font)
        self.coilcoordinateslabel.setObjectName("coilcoordinateslabel")
        self.MplWidget2 = MplWidget(self.frame_6)
        self.MplWidget2.setEnabled(True)
        self.MplWidget2.setGeometry(QtCore.QRect(10, 30, 321, 271))
        self.MplWidget2.setObjectName("MplWidget2")
        self.gridlayout.addWidget(self.frame_6, 0, 0, 2, 1)
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.zeroxinglabel_3 = QtWidgets.QLabel(self.frame_4)
        self.zeroxinglabel_3.setGeometry(QtCore.QRect(6, 86, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.zeroxinglabel_3.setFont(font)
        self.zeroxinglabel_3.setAutoFillBackground(True)
        self.zeroxinglabel_3.setObjectName("zeroxinglabel_3")
        self.trace_commentbox = QtWidgets.QTextEdit(self.frame_4)
        self.trace_commentbox.setGeometry(QtCore.QRect(10, 110, 251, 41))
        self.trace_commentbox.setObjectName("trace_commentbox")
        self.global_commentbox = QtWidgets.QTextEdit(self.frame_4)
        self.global_commentbox.setGeometry(QtCore.QRect(10, 40, 251, 41))
        self.global_commentbox.setObjectName("global_commentbox")
        self.reject_button = QtWidgets.QPushButton(self.frame_4)
        self.reject_button.setGeometry(QtCore.QRect(10, 170, 88, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.reject_button.setFont(font)
        self.reject_button.setObjectName("reject_button")
        self.zeroxinglabel_2 = QtWidgets.QLabel(self.frame_4)
        self.zeroxinglabel_2.setGeometry(QtCore.QRect(6, 16, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.zeroxinglabel_2.setFont(font)
        self.zeroxinglabel_2.setAutoFillBackground(True)
        self.zeroxinglabel_2.setObjectName("zeroxinglabel_2")
        self.gridlayout.addWidget(self.frame_4, 3, 3, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 20, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.trace_idx_num = QtWidgets.QLineEdit(self.frame)
        self.trace_idx_num.setGeometry(QtCore.QRect(160, 20, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.trace_idx_num.setFont(font)
        self.trace_idx_num.setObjectName("trace_idx_num")
        self.last_trace_num = QtWidgets.QLCDNumber(self.frame)
        self.last_trace_num.setGeometry(QtCore.QRect(150, 80, 71, 41))
        self.last_trace_num.setObjectName("last_trace_num")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(40, 80, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.event_time_num = QtWidgets.QLCDNumber(self.frame)
        self.event_time_num.setGeometry(QtCore.QRect(150, 140, 71, 41))
        self.event_time_num.setObjectName("event_time_num")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(50, 140, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.trace_update_button = QtWidgets.QPushButton(self.frame)
        self.trace_update_button.setGeometry(QtCore.QRect(230, 20, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.trace_update_button.setFont(font)
        self.trace_update_button.setObjectName("trace_update_button")
        self.gridlayout.addWidget(self.frame, 3, 1, 1, 1)
        self.frame_7 = QtWidgets.QFrame(self.centralwidget)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.tabWidget = QtWidgets.QTabWidget(self.frame_7)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 321, 291))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.peaklatlabel = QtWidgets.QLabel(self.tab)
        self.peaklatlabel.setGeometry(QtCore.QRect(160, 14, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.peaklatlabel.setFont(font)
        self.peaklatlabel.setAutoFillBackground(True)
        self.peaklatlabel.setObjectName("peaklatlabel")
        self.troughlatlabel = QtWidgets.QLabel(self.tab)
        self.troughlatlabel.setGeometry(QtCore.QRect(160, 100, 112, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.troughlatlabel.setFont(font)
        self.troughlatlabel.setAutoFillBackground(True)
        self.troughlatlabel.setObjectName("troughlatlabel")
        self.troughvoltlabel = QtWidgets.QLabel(self.tab)
        self.troughvoltlabel.setGeometry(QtCore.QRect(10, 100, 130, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.troughvoltlabel.setFont(font)
        self.troughvoltlabel.setAutoFillBackground(True)
        self.troughvoltlabel.setObjectName("troughvoltlabel")
        self.peakvoltlabel = QtWidgets.QLabel(self.tab)
        self.peakvoltlabel.setGeometry(QtCore.QRect(10, 20, 120, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.peakvoltlabel.setFont(font)
        self.peakvoltlabel.setAutoFillBackground(True)
        self.peakvoltlabel.setObjectName("peakvoltlabel")
        self.peaklat_num = QtWidgets.QLineEdit(self.tab)
        self.peaklat_num.setGeometry(QtCore.QRect(160, 50, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.peaklat_num.setFont(font)
        self.peaklat_num.setObjectName("peaklat_num")
        self.troughmag_num = QtWidgets.QLineEdit(self.tab)
        self.troughmag_num.setGeometry(QtCore.QRect(10, 130, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.troughmag_num.setFont(font)
        self.troughmag_num.setObjectName("troughmag_num")
        self.troughlat_num = QtWidgets.QLineEdit(self.tab)
        self.troughlat_num.setGeometry(QtCore.QRect(160, 130, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.troughlat_num.setFont(font)
        self.troughlat_num.setObjectName("troughlat_num")
        self.peakmag_num = QtWidgets.QLineEdit(self.tab)
        self.peakmag_num.setGeometry(QtCore.QRect(10, 50, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.peakmag_num.setFont(font)
        self.peakmag_num.setObjectName("peakmag_num")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.zeroxinglabel = QtWidgets.QLabel(self.tab_2)
        self.zeroxinglabel.setGeometry(QtCore.QRect(10, 80, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.zeroxinglabel.setFont(font)
        self.zeroxinglabel.setAutoFillBackground(True)
        self.zeroxinglabel.setObjectName("zeroxinglabel")
        self.time_since_pulse_label_3 = QtWidgets.QLabel(self.tab_2)
        self.time_since_pulse_label_3.setGeometry(QtCore.QRect(210, 90, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.time_since_pulse_label_3.setFont(font)
        self.time_since_pulse_label_3.setAutoFillBackground(True)
        self.time_since_pulse_label_3.setObjectName("time_since_pulse_label_3")
        self.time_since_pulse_label_2 = QtWidgets.QLabel(self.tab_2)
        self.time_since_pulse_label_2.setGeometry(QtCore.QRect(210, 13, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.time_since_pulse_label_2.setFont(font)
        self.time_since_pulse_label_2.setAutoFillBackground(True)
        self.time_since_pulse_label_2.setObjectName("time_since_pulse_label_2")
        self.time_since_pulse_label = QtWidgets.QLabel(self.tab_2)
        self.time_since_pulse_label.setGeometry(QtCore.QRect(10, 160, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.time_since_pulse_label.setFont(font)
        self.time_since_pulse_label.setAutoFillBackground(True)
        self.time_since_pulse_label.setObjectName("time_since_pulse_label")
        self.stimintensitylabel = QtWidgets.QLabel(self.tab_2)
        self.stimintensitylabel.setGeometry(QtCore.QRect(10, 0, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.stimintensitylabel.setFont(font)
        self.stimintensitylabel.setAutoFillBackground(True)
        self.stimintensitylabel.setObjectName("stimintensitylabel")
        self.zcr_lat_num = QtWidgets.QLineEdit(self.tab_2)
        self.zcr_lat_num.setGeometry(QtCore.QRect(10, 110, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.zcr_lat_num.setFont(font)
        self.zcr_lat_num.setObjectName("zcr_lat_num")
        self.stimintensity_num = QtWidgets.QLineEdit(self.tab_2)
        self.stimintensity_num.setGeometry(QtCore.QRect(10, 30, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.stimintensity_num.setFont(font)
        self.stimintensity_num.setObjectName("stimintensity_num")
        self.onset_shift_num = QtWidgets.QLineEdit(self.tab_2)
        self.onset_shift_num.setGeometry(QtCore.QRect(210, 40, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.onset_shift_num.setFont(font)
        self.onset_shift_num.setObjectName("onset_shift_num")
        self.didt_num = QtWidgets.QLineEdit(self.tab_2)
        self.didt_num.setGeometry(QtCore.QRect(210, 120, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.didt_num.setFont(font)
        self.didt_num.setObjectName("didt_num")
        self.time_since_pulse_num = QtWidgets.QLineEdit(self.tab_2)
        self.time_since_pulse_num.setGeometry(QtCore.QRect(10, 190, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.time_since_pulse_num.setFont(font)
        self.time_since_pulse_num.setObjectName("time_since_pulse_num")
        self.tabWidget.addTab(self.tab_2, "")
        self.gridlayout.addWidget(self.frame_7, 2, 0, 2, 1)
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.MplWidget1 = MplWidget(self.frame_5)
        self.MplWidget1.setGeometry(QtCore.QRect(10, 40, 971, 581))
        self.MplWidget1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.MplWidget1.setObjectName("MplWidget1")
        self.examinerlabel = QtWidgets.QLabel(self.frame_5)
        self.examinerlabel.setGeometry(QtCore.QRect(10, 10, 77, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.examinerlabel.setFont(font)
        self.examinerlabel.setObjectName("examinerlabel")
        self.examiner_name = QtWidgets.QLineEdit(self.frame_5)
        self.examiner_name.setGeometry(QtCore.QRect(90, 10, 167, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.examiner_name.setFont(font)
        self.examiner_name.setObjectName("examiner_name")
        self.filename_label = QtWidgets.QLabel(self.frame_5)
        self.filename_label.setGeometry(QtCore.QRect(290, 10, 74, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.filename_label.setFont(font)
        self.filename_label.setObjectName("filename_label")
        self.filename_label_2 = QtWidgets.QLabel(self.frame_5)
        self.filename_label_2.setGeometry(QtCore.QRect(360, 10, 491, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.filename_label_2.setFont(font)
        self.filename_label_2.setObjectName("filename_label_2")
        self.gridlayout.addWidget(self.frame_5, 0, 1, 3, 3)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.channel_label = QtWidgets.QLabel(self.frame_2)
        self.channel_label.setGeometry(QtCore.QRect(192, -2, 49, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.channel_label.setFont(font)
        self.channel_label.setAutoFillBackground(True)
        self.channel_label.setObjectName("channel_label")
        self.readout = QtWidgets.QLabel(self.frame_2)
        self.readout.setGeometry(QtCore.QRect(202, 43, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.readout.setFont(font)
        self.readout.setObjectName("readout")
        self.muscle_label = QtWidgets.QLabel(self.frame_2)
        self.muscle_label.setGeometry(QtCore.QRect(130, 10, 53, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.muscle_label.setFont(font)
        self.muscle_label.setAutoFillBackground(True)
        self.muscle_label.setObjectName("muscle_label")
        self.readout_label = QtWidgets.QLabel(self.frame_2)
        self.readout_label.setGeometry(QtCore.QRect(130, 43, 64, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.readout_label.setFont(font)
        self.readout_label.setAutoFillBackground(True)
        self.readout_label.setObjectName("readout_label")
        self.update_attrs_button = QtWidgets.QPushButton(self.frame_2)
        self.update_attrs_button.setGeometry(QtCore.QRect(80, 90, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.update_attrs_button.setFont(font)
        self.update_attrs_button.setObjectName("update_attrs_button")
        self.previous_button = QtWidgets.QPushButton(self.frame_2)
        self.previous_button.setGeometry(QtCore.QRect(0, 40, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.previous_button.setFont(font)
        self.previous_button.setObjectName("previous_button")
        self.next_button = QtWidgets.QPushButton(self.frame_2)
        self.next_button.setGeometry(QtCore.QRect(0, 10, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.next_button.setFont(font)
        self.next_button.setObjectName("next_button")
        self.gridlayout.addWidget(self.frame_2, 3, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1352, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.coil_coordinate_input.setText(_translate("MainWindow", "0,0"))
        self.coilcoordinateslabel.setText(_translate("MainWindow", "Coil coordinates: "))
        self.zeroxinglabel_3.setText(_translate("MainWindow", "trace comments:"))
        self.reject_button.setText(_translate("MainWindow", "Reject Trial"))
        self.zeroxinglabel_2.setText(_translate("MainWindow", "file comments:"))
        self.label.setText(_translate("MainWindow", "Enter Trace ID:"))
        self.trace_idx_num.setText(_translate("MainWindow", "0"))
        self.label_2.setText(_translate("MainWindow", "Total Traces: "))
        self.label_3.setText(_translate("MainWindow", "Event Time:"))
        self.trace_update_button.setText(_translate("MainWindow", "Go"))
        self.peaklatlabel.setText(_translate("MainWindow", "peak latency (ms)"))
        self.troughlatlabel.setText(_translate("MainWindow", "trough latency (ms)"))
        self.troughvoltlabel.setText(_translate("MainWindow", "trough magnitude (uV)"))
        self.peakvoltlabel.setText(_translate("MainWindow", "peak magnitude (uV)"))
        self.peaklat_num.setText(_translate("MainWindow", "0"))
        self.troughmag_num.setText(_translate("MainWindow", "0"))
        self.troughlat_num.setText(_translate("MainWindow", "0"))
        self.peakmag_num.setText(_translate("MainWindow", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Mag/Lat"))
        self.zeroxinglabel.setText(_translate("MainWindow", "zero crossing latency (ms)"))
        self.time_since_pulse_label_3.setText(_translate("MainWindow", "di/dt"))
        self.time_since_pulse_label_2.setText(_translate("MainWindow", "onset shift (ms)"))
        self.time_since_pulse_label.setText(_translate("MainWindow", "time since last pulse (ms)"))
        self.stimintensitylabel.setText(_translate("MainWindow", "stim intensity (% MSO)"))
        self.zcr_lat_num.setText(_translate("MainWindow", "0"))
        self.stimintensity_num.setText(_translate("MainWindow", "0"))
        self.onset_shift_num.setText(_translate("MainWindow", "0"))
        self.didt_num.setText(_translate("MainWindow", "0"))
        self.time_since_pulse_num.setText(_translate("MainWindow", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Other"))
        self.examinerlabel.setText(_translate("MainWindow", "Examiner: "))
        self.examiner_name.setText(_translate("MainWindow", "HiWi"))
        self.filename_label.setText(_translate("MainWindow", "Filename: "))
        self.filename_label_2.setText(_translate("MainWindow", "Filename"))
        self.channel_label.setText(_translate("MainWindow", "EDC_R"))
        self.readout.setText(_translate("MainWindow", "Contralateral MEP"))
        self.muscle_label.setText(_translate("MainWindow", "Muscle:"))
        self.readout_label.setText(_translate("MainWindow", "Readout:"))
        self.update_attrs_button.setText(_translate("MainWindow", "Update"))
        self.previous_button.setText(_translate("MainWindow", "Previous"))
        self.next_button.setText(_translate("MainWindow", "Next"))


from .mplwidget import MplWidget
