# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'visual_inspection_gui.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1097, 876)
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMaximumSize(QtCore.QSize(1510, 862))
        self.centralwidget.setAutoFillBackground(True)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(7)
        self.gridLayout.setObjectName("gridLayout")
        self.event_time_num = QtWidgets.QLCDNumber(self.centralwidget)
        self.event_time_num.setAutoFillBackground(True)
        self.event_time_num.setObjectName("event_time_num")
        self.gridLayout.addWidget(self.event_time_num, 12, 3, 1, 1)
        self.reject_button = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.reject_button.setFont(font)
        self.reject_button.setObjectName("reject_button")
        self.gridLayout.addWidget(self.reject_button, 14, 0, 1, 2)
        self.readout_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.readout_label.setFont(font)
        self.readout_label.setAutoFillBackground(True)
        self.readout_label.setObjectName("readout_label")
        self.gridLayout.addWidget(self.readout_label, 14, 2, 1, 1)
        self.commentbox = QtWidgets.QTextEdit(self.centralwidget)
        self.commentbox.setObjectName("commentbox")
        self.gridLayout.addWidget(self.commentbox, 12, 0, 2, 2)
        self.channel_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.channel_label.setFont(font)
        self.channel_label.setAutoFillBackground(True)
        self.channel_label.setObjectName("channel_label")
        self.gridLayout.addWidget(self.channel_label, 13, 3, 1, 1)
        self.muscle_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.muscle_label.setFont(font)
        self.muscle_label.setAutoFillBackground(True)
        self.muscle_label.setObjectName("muscle_label")
        self.gridLayout.addWidget(self.muscle_label, 13, 2, 1, 1)
        self.dataindexlabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dataindexlabel.setFont(font)
        self.dataindexlabel.setAutoFillBackground(True)
        self.dataindexlabel.setObjectName("dataindexlabel")
        self.gridLayout.addWidget(self.dataindexlabel, 10, 2, 2, 1)
        self.event_id_num = QtWidgets.QLCDNumber(self.centralwidget)
        self.event_id_num.setAutoFillBackground(True)
        self.event_id_num.setObjectName("event_id_num")
        self.gridLayout.addWidget(self.event_id_num, 10, 3, 2, 1)
        self.previous_button = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.previous_button.setFont(font)
        self.previous_button.setObjectName("previous_button")
        self.gridLayout.addWidget(self.previous_button, 10, 0, 1, 1)
        self.update_attrs_button = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.update_attrs_button.setFont(font)
        self.update_attrs_button.setObjectName("update_attrs_button")
        self.gridLayout.addWidget(self.update_attrs_button, 14, 9, 1, 1)
        self.next_button = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.next_button.setFont(font)
        self.next_button.setObjectName("next_button")
        self.gridLayout.addWidget(self.next_button, 10, 1, 1, 1)
        self.examiner_name = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.examiner_name.setFont(font)
        self.examiner_name.setObjectName("examiner_name")
        self.gridLayout.addWidget(self.examiner_name, 0, 1, 1, 2)
        self.coil_coordinate_input = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.coil_coordinate_input.setFont(font)
        self.coil_coordinate_input.setObjectName("coil_coordinate_input")
        self.gridLayout.addWidget(self.coil_coordinate_input, 1, 9, 1, 1)
        self.filename_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.filename_label.setFont(font)
        self.filename_label.setObjectName("filename_label")
        self.gridLayout.addWidget(self.filename_label, 0, 3, 1, 1)
        self.filename_label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.filename_label_2.setFont(font)
        self.filename_label_2.setObjectName("filename_label_2")
        self.gridLayout.addWidget(self.filename_label_2, 0, 5, 1, 1)
        self.coilcoordinateslabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.coilcoordinateslabel.setFont(font)
        self.coilcoordinateslabel.setObjectName("coilcoordinateslabel")
        self.gridLayout.addWidget(self.coilcoordinateslabel, 0, 9, 1, 1)
        self.readout = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.readout.setFont(font)
        self.readout.setObjectName("readout")
        self.gridLayout.addWidget(self.readout, 14, 3, 1, 1)
        self.datatimelabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.datatimelabel.setFont(font)
        self.datatimelabel.setAutoFillBackground(True)
        self.datatimelabel.setObjectName("datatimelabel")
        self.gridLayout.addWidget(self.datatimelabel, 12, 2, 1, 1)
        self.examinerlabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.examinerlabel.setFont(font)
        self.examinerlabel.setObjectName("examinerlabel")
        self.gridLayout.addWidget(self.examinerlabel, 0, 0, 1, 1)
        self.zeroxinglabel_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.zeroxinglabel_2.setFont(font)
        self.zeroxinglabel_2.setAutoFillBackground(True)
        self.zeroxinglabel_2.setObjectName("zeroxinglabel_2")
        self.gridLayout.addWidget(self.zeroxinglabel_2, 11, 0, 1, 1)
        self.MplWidget2 = MplWidget2(self.centralwidget)
        self.MplWidget2.setEnabled(True)
        self.MplWidget2.setObjectName("MplWidget2")
        self.gridLayout.addWidget(self.MplWidget2, 2, 9, 8, 1)
        self.MplWidget1 = MplWidget1(self.centralwidget)
        self.MplWidget1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.MplWidget1.setObjectName("MplWidget1")
        self.gridLayout.addWidget(self.MplWidget1, 1, 0, 9, 9)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.peaklatlabel = QtWidgets.QLabel(self.tab)
        self.peaklatlabel.setGeometry(QtCore.QRect(160, 14, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.peaklatlabel.setFont(font)
        self.peaklatlabel.setAutoFillBackground(True)
        self.peaklatlabel.setObjectName("peaklatlabel")
        self.troughlatlabel = QtWidgets.QLabel(self.tab)
        self.troughlatlabel.setGeometry(QtCore.QRect(160, 80, 112, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.troughlatlabel.setFont(font)
        self.troughlatlabel.setAutoFillBackground(True)
        self.troughlatlabel.setObjectName("troughlatlabel")
        self.troughvoltlabel = QtWidgets.QLabel(self.tab)
        self.troughvoltlabel.setGeometry(QtCore.QRect(10, 80, 130, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.troughvoltlabel.setFont(font)
        self.troughvoltlabel.setAutoFillBackground(True)
        self.troughvoltlabel.setObjectName("troughvoltlabel")
        self.peakvoltlabel = QtWidgets.QLabel(self.tab)
        self.peakvoltlabel.setGeometry(QtCore.QRect(10, 20, 120, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.peakvoltlabel.setFont(font)
        self.peakvoltlabel.setAutoFillBackground(True)
        self.peakvoltlabel.setObjectName("peakvoltlabel")
        self.peaklat_num = QtWidgets.QLineEdit(self.tab)
        self.peaklat_num.setGeometry(QtCore.QRect(160, 40, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.peaklat_num.setFont(font)
        self.peaklat_num.setObjectName("peaklat_num")
        self.troughmag_num = QtWidgets.QLineEdit(self.tab)
        self.troughmag_num.setGeometry(QtCore.QRect(10, 110, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.troughmag_num.setFont(font)
        self.troughmag_num.setObjectName("troughmag_num")
        self.troughlat_num = QtWidgets.QLineEdit(self.tab)
        self.troughlat_num.setGeometry(QtCore.QRect(160, 110, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.troughlat_num.setFont(font)
        self.troughlat_num.setObjectName("troughlat_num")
        self.peakmag_num = QtWidgets.QLineEdit(self.tab)
        self.peakmag_num.setGeometry(QtCore.QRect(10, 40, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.peakmag_num.setFont(font)
        self.peakmag_num.setObjectName("peakmag_num")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.zeroxinglabel = QtWidgets.QLabel(self.tab_2)
        self.zeroxinglabel.setGeometry(QtCore.QRect(10, 70, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.zeroxinglabel.setFont(font)
        self.zeroxinglabel.setAutoFillBackground(True)
        self.zeroxinglabel.setObjectName("zeroxinglabel")
        self.time_since_pulse_label_3 = QtWidgets.QLabel(self.tab_2)
        self.time_since_pulse_label_3.setGeometry(QtCore.QRect(210, 70, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.time_since_pulse_label_3.setFont(font)
        self.time_since_pulse_label_3.setAutoFillBackground(True)
        self.time_since_pulse_label_3.setObjectName("time_since_pulse_label_3")
        self.time_since_pulse_label_2 = QtWidgets.QLabel(self.tab_2)
        self.time_since_pulse_label_2.setGeometry(QtCore.QRect(210, 13, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.time_since_pulse_label_2.setFont(font)
        self.time_since_pulse_label_2.setAutoFillBackground(True)
        self.time_since_pulse_label_2.setObjectName("time_since_pulse_label_2")
        self.time_since_pulse_label = QtWidgets.QLabel(self.tab_2)
        self.time_since_pulse_label.setGeometry(QtCore.QRect(10, 127, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.time_since_pulse_label.setFont(font)
        self.time_since_pulse_label.setAutoFillBackground(True)
        self.time_since_pulse_label.setObjectName("time_since_pulse_label")
        self.stimintensitylabel = QtWidgets.QLabel(self.tab_2)
        self.stimintensitylabel.setGeometry(QtCore.QRect(10, 10, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.stimintensitylabel.setFont(font)
        self.stimintensitylabel.setAutoFillBackground(True)
        self.stimintensitylabel.setObjectName("stimintensitylabel")
        self.zcr_lat_num = QtWidgets.QLineEdit(self.tab_2)
        self.zcr_lat_num.setGeometry(QtCore.QRect(10, 87, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.zcr_lat_num.setFont(font)
        self.zcr_lat_num.setObjectName("zcr_lat_num")
        self.stimintensity_num = QtWidgets.QLineEdit(self.tab_2)
        self.stimintensity_num.setGeometry(QtCore.QRect(10, 30, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.stimintensity_num.setFont(font)
        self.stimintensity_num.setObjectName("stimintensity_num")
        self.onset_shift_num = QtWidgets.QLineEdit(self.tab_2)
        self.onset_shift_num.setGeometry(QtCore.QRect(210, 30, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.onset_shift_num.setFont(font)
        self.onset_shift_num.setObjectName("onset_shift_num")
        self.didt_num = QtWidgets.QLineEdit(self.tab_2)
        self.didt_num.setGeometry(QtCore.QRect(210, 90, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.didt_num.setFont(font)
        self.didt_num.setObjectName("didt_num")
        self.time_since_pulse_num = QtWidgets.QLineEdit(self.tab_2)
        self.time_since_pulse_num.setGeometry(QtCore.QRect(10, 147, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.time_since_pulse_num.setFont(font)
        self.time_since_pulse_num.setObjectName("time_since_pulse_num")
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 10, 9, 4, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1097, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.reject_button.setText(_translate("MainWindow", "Reject Trial"))
        self.readout_label.setText(_translate("MainWindow", "Readout:"))
        self.channel_label.setText(_translate("MainWindow", "EDC_R"))
        self.muscle_label.setText(_translate("MainWindow", "Muscle:"))
        self.dataindexlabel.setText(_translate("MainWindow", "event ID:"))
        self.previous_button.setText(_translate("MainWindow", "Previous"))
        self.update_attrs_button.setText(_translate("MainWindow", "Update Attributes"))
        self.next_button.setText(_translate("MainWindow", "Next"))
        self.examiner_name.setText(_translate("MainWindow", "HiWi"))
        self.coil_coordinate_input.setText(_translate("MainWindow", "0,0"))
        self.filename_label.setText(_translate("MainWindow", "Filename: "))
        self.filename_label_2.setText(_translate("MainWindow", "Filename"))
        self.coilcoordinateslabel.setText(_translate("MainWindow", "Coil coordinates: "))
        self.readout.setText(_translate("MainWindow", "Contralateral MEP"))
        self.datatimelabel.setText(_translate("MainWindow", "time (ms):"))
        self.examinerlabel.setText(_translate("MainWindow", "Examiner: "))
        self.zeroxinglabel_2.setText(_translate("MainWindow", "comments:"))
        self.peaklatlabel.setText(_translate("MainWindow", "peak latency (ms)"))
        self.troughlatlabel.setText(_translate("MainWindow", "trough latency (ms)"))
        self.troughvoltlabel.setText(_translate("MainWindow", "trough magnitude (uV)"))
        self.peakvoltlabel.setText(_translate("MainWindow", "peak magnitude (uV)"))
        self.peaklat_num.setText(_translate("MainWindow", "0"))
        self.troughmag_num.setText(_translate("MainWindow", "0"))
        self.troughlat_num.setText(_translate("MainWindow", "0"))
        self.peakmag_num.setText(_translate("MainWindow", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Mag/Lat"))
        self.zeroxinglabel.setText(_translate("MainWindow", "zero crossing latency (ms)"))
        self.time_since_pulse_label_3.setText(_translate("MainWindow", "di/dt"))
        self.time_since_pulse_label_2.setText(_translate("MainWindow", "onset shift (ms)"))
        self.time_since_pulse_label.setText(_translate("MainWindow", "time since last pulse (ms)"))
        self.stimintensitylabel.setText(_translate("MainWindow", "stim intensity (% MSO)"))
        self.zcr_lat_num.setText(_translate("MainWindow", "0"))
        self.stimintensity_num.setText(_translate("MainWindow", "0"))
        self.onset_shift_num.setText(_translate("MainWindow", "0"))
        self.didt_num.setText(_translate("MainWindow", "0"))
        self.time_since_pulse_num.setText(_translate("MainWindow", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Other"))
from offspect.gui.mplwidget import MplWidget1, MplWidget2
