# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'visual_inspection_gui_LR.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(881, 633)
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMaximumSize(QtCore.QSize(1510, 862))
        self.centralwidget.setAutoFillBackground(True)
        self.centralwidget.setObjectName("centralwidget")
        self.event_time_num = QtWidgets.QLCDNumber(self.centralwidget)
        self.event_time_num.setGeometry(QtCore.QRect(373, 370, 64, 23))
        self.event_time_num.setAutoFillBackground(True)
        self.event_time_num.setObjectName("event_time_num")
        self.reject_button = QtWidgets.QPushButton(self.centralwidget)
        self.reject_button.setGeometry(QtCore.QRect(10, 470, 110, 32))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.reject_button.setFont(font)
        self.reject_button.setObjectName("reject_button")
        self.readout_label = QtWidgets.QLabel(self.centralwidget)
        self.readout_label.setGeometry(QtCore.QRect(270, 440, 71, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.readout_label.setFont(font)
        self.readout_label.setAutoFillBackground(True)
        self.readout_label.setObjectName("readout_label")
        self.commentbox = QtWidgets.QTextEdit(self.centralwidget)
        self.commentbox.setGeometry(QtCore.QRect(10, 400, 251, 61))
        self.commentbox.setObjectName("commentbox")
        self.channel_label = QtWidgets.QLabel(self.centralwidget)
        self.channel_label.setGeometry(QtCore.QRect(350, 410, 60, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.channel_label.setFont(font)
        self.channel_label.setAutoFillBackground(True)
        self.channel_label.setObjectName("channel_label")
        self.muscle_label = QtWidgets.QLabel(self.centralwidget)
        self.muscle_label.setGeometry(QtCore.QRect(270, 410, 77, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.muscle_label.setFont(font)
        self.muscle_label.setAutoFillBackground(True)
        self.muscle_label.setObjectName("muscle_label")
        self.dataindexlabel = QtWidgets.QLabel(self.centralwidget)
        self.dataindexlabel.setGeometry(QtCore.QRect(270, 341, 84, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dataindexlabel.setFont(font)
        self.dataindexlabel.setAutoFillBackground(True)
        self.dataindexlabel.setObjectName("dataindexlabel")
        self.event_id_num = QtWidgets.QLCDNumber(self.centralwidget)
        self.event_id_num.setGeometry(QtCore.QRect(373, 341, 64, 23))
        self.event_id_num.setAutoFillBackground(True)
        self.event_id_num.setObjectName("event_id_num")
        self.previous_button = QtWidgets.QPushButton(self.centralwidget)
        self.previous_button.setGeometry(QtCore.QRect(10, 328, 92, 36))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.previous_button.setFont(font)
        self.previous_button.setObjectName("previous_button")
        self.update_attrs_button = QtWidgets.QPushButton(self.centralwidget)
        self.update_attrs_button.setGeometry(QtCore.QRect(330, 490, 165, 32))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.update_attrs_button.setFont(font)
        self.update_attrs_button.setObjectName("update_attrs_button")
        self.next_button = QtWidgets.QPushButton(self.centralwidget)
        self.next_button.setGeometry(QtCore.QRect(141, 328, 75, 36))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.next_button.setFont(font)
        self.next_button.setObjectName("next_button")
        self.examiner_name = QtWidgets.QLineEdit(self.centralwidget)
        self.examiner_name.setGeometry(QtCore.QRect(70, 10, 101, 30))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.examiner_name.setFont(font)
        self.examiner_name.setObjectName("examiner_name")
        self.coil_coordinate_input = QtWidgets.QLineEdit(self.centralwidget)
        self.coil_coordinate_input.setGeometry(QtCore.QRect(624, 45, 167, 27))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.coil_coordinate_input.setFont(font)
        self.coil_coordinate_input.setObjectName("coil_coordinate_input")
        self.filename_label = QtWidgets.QLabel(self.centralwidget)
        self.filename_label.setGeometry(QtCore.QRect(190, 10, 94, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.filename_label.setFont(font)
        self.filename_label.setObjectName("filename_label")
        self.filename_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.filename_label_2.setGeometry(QtCore.QRect(260, 10, 81, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.filename_label_2.setFont(font)
        self.filename_label_2.setObjectName("filename_label_2")
        self.coilcoordinateslabel = QtWidgets.QLabel(self.centralwidget)
        self.coilcoordinateslabel.setGeometry(QtCore.QRect(624, 9, 155, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.coilcoordinateslabel.setFont(font)
        self.coilcoordinateslabel.setObjectName("coilcoordinateslabel")
        self.readout = QtWidgets.QLabel(self.centralwidget)
        self.readout.setGeometry(QtCore.QRect(350, 440, 133, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.readout.setFont(font)
        self.readout.setObjectName("readout")
        self.datatimelabel = QtWidgets.QLabel(self.centralwidget)
        self.datatimelabel.setGeometry(QtCore.QRect(270, 370, 95, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.datatimelabel.setFont(font)
        self.datatimelabel.setAutoFillBackground(True)
        self.datatimelabel.setObjectName("datatimelabel")
        self.examinerlabel = QtWidgets.QLabel(self.centralwidget)
        self.examinerlabel.setGeometry(QtCore.QRect(9, 9, 96, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.examinerlabel.setFont(font)
        self.examinerlabel.setObjectName("examinerlabel")
        self.zeroxinglabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.zeroxinglabel_2.setGeometry(QtCore.QRect(10, 370, 83, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.zeroxinglabel_2.setFont(font)
        self.zeroxinglabel_2.setAutoFillBackground(True)
        self.zeroxinglabel_2.setObjectName("zeroxinglabel_2")
        self.MplWidget2 = MplWidget(self.centralwidget)
        self.MplWidget2.setEnabled(True)
        self.MplWidget2.setGeometry(QtCore.QRect(624, 78, 241, 251))
        self.MplWidget2.setObjectName("MplWidget2")
        self.MplWidget1 = MplWidget(self.centralwidget)
        self.MplWidget1.setGeometry(QtCore.QRect(9, 45, 609, 281))
        self.MplWidget1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.MplWidget1.setObjectName("MplWidget1")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(500, 340, 311, 231))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.peaklatlabel = QtWidgets.QLabel(self.tab)
        self.peaklatlabel.setGeometry(QtCore.QRect(150, 14, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.peaklatlabel.setFont(font)
        self.peaklatlabel.setAutoFillBackground(True)
        self.peaklatlabel.setObjectName("peaklatlabel")
        self.troughlatlabel = QtWidgets.QLabel(self.tab)
        self.troughlatlabel.setGeometry(QtCore.QRect(150, 60, 112, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.troughlatlabel.setFont(font)
        self.troughlatlabel.setAutoFillBackground(True)
        self.troughlatlabel.setObjectName("troughlatlabel")
        self.troughvoltlabel = QtWidgets.QLabel(self.tab)
        self.troughvoltlabel.setGeometry(QtCore.QRect(10, 60, 130, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.troughvoltlabel.setFont(font)
        self.troughvoltlabel.setAutoFillBackground(True)
        self.troughvoltlabel.setObjectName("troughvoltlabel")
        self.peakvoltlabel = QtWidgets.QLabel(self.tab)
        self.peakvoltlabel.setGeometry(QtCore.QRect(10, 20, 120, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.peakvoltlabel.setFont(font)
        self.peakvoltlabel.setAutoFillBackground(True)
        self.peakvoltlabel.setObjectName("peakvoltlabel")
        self.peaklat_num = QtWidgets.QLineEdit(self.tab)
        self.peaklat_num.setGeometry(QtCore.QRect(150, 40, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.peaklat_num.setFont(font)
        self.peaklat_num.setObjectName("peaklat_num")
        self.troughmag_num = QtWidgets.QLineEdit(self.tab)
        self.troughmag_num.setGeometry(QtCore.QRect(10, 80, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.troughmag_num.setFont(font)
        self.troughmag_num.setObjectName("troughmag_num")
        self.troughlat_num = QtWidgets.QLineEdit(self.tab)
        self.troughlat_num.setGeometry(QtCore.QRect(150, 80, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.troughlat_num.setFont(font)
        self.troughlat_num.setObjectName("troughlat_num")
        self.peakmag_num = QtWidgets.QLineEdit(self.tab)
        self.peakmag_num.setGeometry(QtCore.QRect(10, 40, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.peakmag_num.setFont(font)
        self.peakmag_num.setObjectName("peakmag_num")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.zeroxinglabel = QtWidgets.QLabel(self.tab_2)
        self.zeroxinglabel.setGeometry(QtCore.QRect(10, 50, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.zeroxinglabel.setFont(font)
        self.zeroxinglabel.setAutoFillBackground(True)
        self.zeroxinglabel.setObjectName("zeroxinglabel")
        self.time_since_pulse_label_3 = QtWidgets.QLabel(self.tab_2)
        self.time_since_pulse_label_3.setGeometry(QtCore.QRect(170, 50, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.time_since_pulse_label_3.setFont(font)
        self.time_since_pulse_label_3.setAutoFillBackground(True)
        self.time_since_pulse_label_3.setObjectName("time_since_pulse_label_3")
        self.time_since_pulse_label_2 = QtWidgets.QLabel(self.tab_2)
        self.time_since_pulse_label_2.setGeometry(QtCore.QRect(170, 13, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.time_since_pulse_label_2.setFont(font)
        self.time_since_pulse_label_2.setAutoFillBackground(True)
        self.time_since_pulse_label_2.setObjectName("time_since_pulse_label_2")
        self.time_since_pulse_label = QtWidgets.QLabel(self.tab_2)
        self.time_since_pulse_label.setGeometry(QtCore.QRect(10, 90, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.time_since_pulse_label.setFont(font)
        self.time_since_pulse_label.setAutoFillBackground(True)
        self.time_since_pulse_label.setObjectName("time_since_pulse_label")
        self.stimintensitylabel = QtWidgets.QLabel(self.tab_2)
        self.stimintensitylabel.setGeometry(QtCore.QRect(10, 10, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.stimintensitylabel.setFont(font)
        self.stimintensitylabel.setAutoFillBackground(True)
        self.stimintensitylabel.setObjectName("stimintensitylabel")
        self.zcr_lat_num = QtWidgets.QLineEdit(self.tab_2)
        self.zcr_lat_num.setGeometry(QtCore.QRect(10, 67, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.zcr_lat_num.setFont(font)
        self.zcr_lat_num.setObjectName("zcr_lat_num")
        self.stimintensity_num = QtWidgets.QLineEdit(self.tab_2)
        self.stimintensity_num.setGeometry(QtCore.QRect(10, 30, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.stimintensity_num.setFont(font)
        self.stimintensity_num.setObjectName("stimintensity_num")
        self.onset_shift_num = QtWidgets.QLineEdit(self.tab_2)
        self.onset_shift_num.setGeometry(QtCore.QRect(170, 30, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.onset_shift_num.setFont(font)
        self.onset_shift_num.setObjectName("onset_shift_num")
        self.didt_num = QtWidgets.QLineEdit(self.tab_2)
        self.didt_num.setGeometry(QtCore.QRect(170, 70, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.didt_num.setFont(font)
        self.didt_num.setObjectName("didt_num")
        self.time_since_pulse_num = QtWidgets.QLineEdit(self.tab_2)
        self.time_since_pulse_num.setGeometry(QtCore.QRect(10, 110, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.time_since_pulse_num.setFont(font)
        self.time_since_pulse_num.setObjectName("time_since_pulse_num")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 881, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.reject_button.setText(_translate("MainWindow", "Reject Trial"))
        self.readout_label.setText(_translate("MainWindow", "Readout:"))
        self.channel_label.setText(_translate("MainWindow", "EDC_R"))
        self.muscle_label.setText(_translate("MainWindow", "Muscle:"))
        self.dataindexlabel.setText(_translate("MainWindow", "event ID:"))
        self.previous_button.setText(_translate("MainWindow", "Previous"))
        self.update_attrs_button.setText(_translate("MainWindow", "Update Attributes"))
        self.next_button.setText(_translate("MainWindow", "Next"))
        self.examiner_name.setText(_translate("MainWindow", "HiWi"))
        self.coil_coordinate_input.setText(_translate("MainWindow", "0,0"))
        self.filename_label.setText(_translate("MainWindow", "Filename: "))
        self.filename_label_2.setText(_translate("MainWindow", "Filename"))
        self.coilcoordinateslabel.setText(_translate("MainWindow", "Coil coordinates: "))
        self.readout.setText(_translate("MainWindow", "Contralateral MEP"))
        self.datatimelabel.setText(_translate("MainWindow", "time (ms):"))
        self.examinerlabel.setText(_translate("MainWindow", "Examiner: "))
        self.zeroxinglabel_2.setText(_translate("MainWindow", "comments:"))
        self.peaklatlabel.setText(_translate("MainWindow", "peak latency (ms)"))
        self.troughlatlabel.setText(_translate("MainWindow", "trough latency (ms)"))
        self.troughvoltlabel.setText(_translate("MainWindow", "trough magnitude (uV)"))
        self.peakvoltlabel.setText(_translate("MainWindow", "peak magnitude (uV)"))
        self.peaklat_num.setText(_translate("MainWindow", "0"))
        self.troughmag_num.setText(_translate("MainWindow", "0"))
        self.troughlat_num.setText(_translate("MainWindow", "0"))
        self.peakmag_num.setText(_translate("MainWindow", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Mag/Lat"))
        self.zeroxinglabel.setText(_translate("MainWindow", "zero crossing latency (ms)"))
        self.time_since_pulse_label_3.setText(_translate("MainWindow", "di/dt"))
        self.time_since_pulse_label_2.setText(_translate("MainWindow", "onset shift (ms)"))
        self.time_since_pulse_label.setText(_translate("MainWindow", "time since last pulse (ms)"))
        self.stimintensitylabel.setText(_translate("MainWindow", "stim intensity (% MSO)"))
        self.zcr_lat_num.setText(_translate("MainWindow", "0"))
        self.stimintensity_num.setText(_translate("MainWindow", "0"))
        self.onset_shift_num.setText(_translate("MainWindow", "0"))
        self.didt_num.setText(_translate("MainWindow", "0"))
        self.time_since_pulse_num.setText(_translate("MainWindow", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Other"))

from .mplwidget import MplWidget
