# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'visual_inspection_gui_XS.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(851, 589)
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMaximumSize(QtCore.QSize(1510, 862))
        self.centralwidget.setAutoFillBackground(True)
        self.centralwidget.setObjectName("centralwidget")
        self.previous_button = QtWidgets.QPushButton(self.centralwidget)
        self.previous_button.setGeometry(QtCore.QRect(360, 412, 93, 37))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.previous_button.setFont(font)
        self.previous_button.setObjectName("previous_button")
        self.filename_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.filename_label_2.setGeometry(QtCore.QRect(640, 0, 201, 24))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.filename_label_2.setFont(font)
        self.filename_label_2.setObjectName("filename_label_2")
        self.reject_button = QtWidgets.QPushButton(self.centralwidget)
        self.reject_button.setGeometry(QtCore.QRect(170, 310, 111, 33))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.reject_button.setFont(font)
        self.reject_button.setObjectName("reject_button")
        self.next_button = QtWidgets.QPushButton(self.centralwidget)
        self.next_button.setGeometry(QtCore.QRect(360, 372, 93, 37))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.next_button.setFont(font)
        self.next_button.setObjectName("next_button")
        self.update_attrs_button = QtWidgets.QPushButton(self.centralwidget)
        self.update_attrs_button.setGeometry(QtCore.QRect(50, 310, 93, 33))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.update_attrs_button.setFont(font)
        self.update_attrs_button.setObjectName("update_attrs_button")
        self.examiner_name = QtWidgets.QLineEdit(self.centralwidget)
        self.examiner_name.setGeometry(QtCore.QRect(360, 0, 205, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.examiner_name.setFont(font)
        self.examiner_name.setObjectName("examiner_name")
        self.muscle_label = QtWidgets.QLabel(self.centralwidget)
        self.muscle_label.setGeometry(QtCore.QRect(665, 470, 67, 24))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.muscle_label.setFont(font)
        self.muscle_label.setAutoFillBackground(True)
        self.muscle_label.setObjectName("muscle_label")
        self.commentbox = QtWidgets.QTextEdit(self.centralwidget)
        self.commentbox.setGeometry(QtCore.QRect(650, 392, 191, 71))
        self.commentbox.setObjectName("commentbox")
        self.filename_label = QtWidgets.QLabel(self.centralwidget)
        self.filename_label.setGeometry(QtCore.QRect(570, 0, 94, 24))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.filename_label.setFont(font)
        self.filename_label.setObjectName("filename_label")
        self.MplWidget1 = MplWidget(self.centralwidget)
        self.MplWidget1.setGeometry(QtCore.QRect(300, 40, 541, 311))
        self.MplWidget1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.MplWidget1.setObjectName("MplWidget1")
        self.channel_label = QtWidgets.QLabel(self.centralwidget)
        self.channel_label.setGeometry(QtCore.QRect(735, 470, 60, 24))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.channel_label.setFont(font)
        self.channel_label.setAutoFillBackground(True)
        self.channel_label.setObjectName("channel_label")
        self.coilcoordinateslabel = QtWidgets.QLabel(self.centralwidget)
        self.coilcoordinateslabel.setGeometry(QtCore.QRect(1, 3, 155, 24))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.coilcoordinateslabel.setFont(font)
        self.coilcoordinateslabel.setObjectName("coilcoordinateslabel")
        self.readout_label = QtWidgets.QLabel(self.centralwidget)
        self.readout_label.setGeometry(QtCore.QRect(655, 500, 71, 24))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.readout_label.setFont(font)
        self.readout_label.setAutoFillBackground(True)
        self.readout_label.setObjectName("readout_label")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 360, 351, 171))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.peaklatlabel = QtWidgets.QLabel(self.tab_7)
        self.peaklatlabel.setGeometry(QtCore.QRect(160, 4, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.peaklatlabel.setFont(font)
        self.peaklatlabel.setAutoFillBackground(True)
        self.peaklatlabel.setObjectName("peaklatlabel")
        self.troughlatlabel = QtWidgets.QLabel(self.tab_7)
        self.troughlatlabel.setGeometry(QtCore.QRect(160, 50, 112, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.troughlatlabel.setFont(font)
        self.troughlatlabel.setAutoFillBackground(True)
        self.troughlatlabel.setObjectName("troughlatlabel")
        self.troughvoltlabel = QtWidgets.QLabel(self.tab_7)
        self.troughvoltlabel.setGeometry(QtCore.QRect(10, 50, 130, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.troughvoltlabel.setFont(font)
        self.troughvoltlabel.setAutoFillBackground(True)
        self.troughvoltlabel.setObjectName("troughvoltlabel")
        self.peakvoltlabel = QtWidgets.QLabel(self.tab_7)
        self.peakvoltlabel.setGeometry(QtCore.QRect(10, 10, 120, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.peakvoltlabel.setFont(font)
        self.peakvoltlabel.setAutoFillBackground(True)
        self.peakvoltlabel.setObjectName("peakvoltlabel")
        self.peaklat_num = QtWidgets.QLineEdit(self.tab_7)
        self.peaklat_num.setGeometry(QtCore.QRect(160, 30, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.peaklat_num.setFont(font)
        self.peaklat_num.setObjectName("peaklat_num")
        self.troughmag_num = QtWidgets.QLineEdit(self.tab_7)
        self.troughmag_num.setGeometry(QtCore.QRect(10, 70, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.troughmag_num.setFont(font)
        self.troughmag_num.setObjectName("troughmag_num")
        self.troughlat_num = QtWidgets.QLineEdit(self.tab_7)
        self.troughlat_num.setGeometry(QtCore.QRect(160, 70, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.troughlat_num.setFont(font)
        self.troughlat_num.setObjectName("troughlat_num")
        self.peakmag_num = QtWidgets.QLineEdit(self.tab_7)
        self.peakmag_num.setGeometry(QtCore.QRect(10, 30, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.peakmag_num.setFont(font)
        self.peakmag_num.setObjectName("peakmag_num")
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.zeroxinglabel_4 = QtWidgets.QLabel(self.tab_8)
        self.zeroxinglabel_4.setGeometry(QtCore.QRect(10, 50, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.zeroxinglabel_4.setFont(font)
        self.zeroxinglabel_4.setAutoFillBackground(True)
        self.zeroxinglabel_4.setObjectName("zeroxinglabel_4")
        self.time_since_pulse_label_10 = QtWidgets.QLabel(self.tab_8)
        self.time_since_pulse_label_10.setGeometry(QtCore.QRect(210, 60, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.time_since_pulse_label_10.setFont(font)
        self.time_since_pulse_label_10.setAutoFillBackground(True)
        self.time_since_pulse_label_10.setObjectName("time_since_pulse_label_10")
        self.time_since_pulse_label_11 = QtWidgets.QLabel(self.tab_8)
        self.time_since_pulse_label_11.setGeometry(QtCore.QRect(210, 13, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.time_since_pulse_label_11.setFont(font)
        self.time_since_pulse_label_11.setAutoFillBackground(True)
        self.time_since_pulse_label_11.setObjectName("time_since_pulse_label_11")
        self.time_since_pulse_label_12 = QtWidgets.QLabel(self.tab_8)
        self.time_since_pulse_label_12.setGeometry(QtCore.QRect(10, 90, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.time_since_pulse_label_12.setFont(font)
        self.time_since_pulse_label_12.setAutoFillBackground(True)
        self.time_since_pulse_label_12.setObjectName("time_since_pulse_label_12")
        self.stimintensitylabel = QtWidgets.QLabel(self.tab_8)
        self.stimintensitylabel.setGeometry(QtCore.QRect(10, 10, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.stimintensitylabel.setFont(font)
        self.stimintensitylabel.setAutoFillBackground(True)
        self.stimintensitylabel.setObjectName("stimintensitylabel")
        self.zcr_lat_num = QtWidgets.QLineEdit(self.tab_8)
        self.zcr_lat_num.setGeometry(QtCore.QRect(10, 70, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.zcr_lat_num.setFont(font)
        self.zcr_lat_num.setObjectName("zcr_lat_num")
        self.stimintensity_num = QtWidgets.QLineEdit(self.tab_8)
        self.stimintensity_num.setGeometry(QtCore.QRect(10, 30, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.stimintensity_num.setFont(font)
        self.stimintensity_num.setObjectName("stimintensity_num")
        self.onset_shift_num = QtWidgets.QLineEdit(self.tab_8)
        self.onset_shift_num.setGeometry(QtCore.QRect(210, 30, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.onset_shift_num.setFont(font)
        self.onset_shift_num.setObjectName("onset_shift_num")
        self.didt_num = QtWidgets.QLineEdit(self.tab_8)
        self.didt_num.setGeometry(QtCore.QRect(210, 80, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.didt_num.setFont(font)
        self.didt_num.setObjectName("didt_num")
        self.time_since_pulse_num = QtWidgets.QLineEdit(self.tab_8)
        self.time_since_pulse_num.setGeometry(QtCore.QRect(10, 110, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.time_since_pulse_num.setFont(font)
        self.time_since_pulse_num.setObjectName("time_since_pulse_num")
        self.tabWidget.addTab(self.tab_8, "")
        self.examinerlabel = QtWidgets.QLabel(self.centralwidget)
        self.examinerlabel.setGeometry(QtCore.QRect(290, 0, 96, 24))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.examinerlabel.setFont(font)
        self.examinerlabel.setObjectName("examinerlabel")
        self.coil_coordinate_input = QtWidgets.QLineEdit(self.centralwidget)
        self.coil_coordinate_input.setGeometry(QtCore.QRect(1, 40, 171, 27))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.coil_coordinate_input.setFont(font)
        self.coil_coordinate_input.setObjectName("coil_coordinate_input")
        self.MplWidget2 = MplWidget(self.centralwidget)
        self.MplWidget2.setEnabled(True)
        self.MplWidget2.setGeometry(QtCore.QRect(1, 74, 291, 221))
        self.MplWidget2.setObjectName("MplWidget2")
        self.zeroxinglabel_5 = QtWidgets.QLabel(self.centralwidget)
        self.zeroxinglabel_5.setGeometry(QtCore.QRect(650, 362, 83, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.zeroxinglabel_5.setFont(font)
        self.zeroxinglabel_5.setAutoFillBackground(True)
        self.zeroxinglabel_5.setObjectName("zeroxinglabel_5")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(460, 372, 191, 171))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.frame.setFont(font)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(10, 0, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.trace_idx_num = QtWidgets.QLineEdit(self.frame)
        self.trace_idx_num.setGeometry(QtCore.QRect(120, 0, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.trace_idx_num.setFont(font)
        self.trace_idx_num.setObjectName("trace_idx_num")
        self.last_trace_num = QtWidgets.QLCDNumber(self.frame)
        self.last_trace_num.setGeometry(QtCore.QRect(100, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.last_trace_num.setFont(font)
        self.last_trace_num.setObjectName("last_trace_num")
        self.total_traces_label = QtWidgets.QLabel(self.frame)
        self.total_traces_label.setGeometry(QtCore.QRect(10, 70, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.total_traces_label.setFont(font)
        self.total_traces_label.setObjectName("total_traces_label")
        self.event_time_num = QtWidgets.QLCDNumber(self.frame)
        self.event_time_num.setGeometry(QtCore.QRect(100, 120, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.event_time_num.setFont(font)
        self.event_time_num.setObjectName("event_time_num")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(10, 110, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.trace_update_button = QtWidgets.QPushButton(self.frame)
        self.trace_update_button.setGeometry(QtCore.QRect(10, 30, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.trace_update_button.setFont(font)
        self.trace_update_button.setObjectName("trace_update_button")
        self.readout = QtWidgets.QLabel(self.centralwidget)
        self.readout.setGeometry(QtCore.QRect(730, 500, 133, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.readout.setFont(font)
        self.readout.setObjectName("readout")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 851, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.previous_button.setText(_translate("MainWindow", "Previous"))
        self.filename_label_2.setText(_translate("MainWindow", "Filename"))
        self.reject_button.setText(_translate("MainWindow", "Reject Trial"))
        self.next_button.setText(_translate("MainWindow", "Next"))
        self.update_attrs_button.setText(_translate("MainWindow", "Update"))
        self.examiner_name.setText(_translate("MainWindow", "HiWi"))
        self.muscle_label.setText(_translate("MainWindow", "Muscle:"))
        self.filename_label.setText(_translate("MainWindow", "Filename: "))
        self.channel_label.setText(_translate("MainWindow", "EDC_R"))
        self.coilcoordinateslabel.setText(_translate("MainWindow", "Coil coordinates: "))
        self.readout_label.setText(_translate("MainWindow", "Readout:"))
        self.peaklatlabel.setText(_translate("MainWindow", "peak latency (ms)"))
        self.troughlatlabel.setText(_translate("MainWindow", "trough latency (ms)"))
        self.troughvoltlabel.setText(_translate("MainWindow", "trough magnitude (uV)"))
        self.peakvoltlabel.setText(_translate("MainWindow", "peak magnitude (uV)"))
        self.peaklat_num.setText(_translate("MainWindow", "0"))
        self.troughmag_num.setText(_translate("MainWindow", "0"))
        self.troughlat_num.setText(_translate("MainWindow", "0"))
        self.peakmag_num.setText(_translate("MainWindow", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainWindow", "Mag/Lat"))
        self.zeroxinglabel_4.setText(_translate("MainWindow", "zero crossing latency (ms)"))
        self.time_since_pulse_label_10.setText(_translate("MainWindow", "di/dt"))
        self.time_since_pulse_label_11.setText(_translate("MainWindow", "onset shift (ms)"))
        self.time_since_pulse_label_12.setText(_translate("MainWindow", "time since last pulse (ms)"))
        self.stimintensitylabel.setText(_translate("MainWindow", "stim intensity (% MSO)"))
        self.zcr_lat_num.setText(_translate("MainWindow", "0"))
        self.stimintensity_num.setText(_translate("MainWindow", "0"))
        self.onset_shift_num.setText(_translate("MainWindow", "0"))
        self.didt_num.setText(_translate("MainWindow", "0"))
        self.time_since_pulse_num.setText(_translate("MainWindow", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("MainWindow", "Other"))
        self.examinerlabel.setText(_translate("MainWindow", "Examiner: "))
        self.coil_coordinate_input.setText(_translate("MainWindow", "0,0"))
        self.zeroxinglabel_5.setText(_translate("MainWindow", "comments:"))
        self.label_7.setText(_translate("MainWindow", "Enter Trace ID:"))
        self.trace_idx_num.setText(_translate("MainWindow", "1"))
        self.total_traces_label.setText(_translate("MainWindow", "Total Traces: "))
        self.label_9.setText(_translate("MainWindow", "Event Time:"))
        self.trace_update_button.setText(_translate("MainWindow", "Go"))
        self.readout.setText(_translate("MainWindow", "Contralateral MEP"))

from .mplwidget import MplWidget
