# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'visual_inspection_gui.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1243, 1014)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.zeroxinglabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.zeroxinglabel_2.setGeometry(QtCore.QRect(20, 650, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.zeroxinglabel_2.setFont(font)
        self.zeroxinglabel_2.setAutoFillBackground(True)
        self.zeroxinglabel_2.setObjectName("zeroxinglabel_2")
        self.commentbox = QtWidgets.QTextEdit(self.centralwidget)
        self.commentbox.setGeometry(QtCore.QRect(20, 670, 191, 101))
        self.commentbox.setObjectName("commentbox")
        self.examinerlabel = QtWidgets.QLabel(self.centralwidget)
        self.examinerlabel.setGeometry(QtCore.QRect(10, 0, 101, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.examinerlabel.setFont(font)
        self.examinerlabel.setObjectName("examinerlabel")
        self.event_id_num = QtWidgets.QLCDNumber(self.centralwidget)
        self.event_id_num.setGeometry(QtCore.QRect(300, 550, 111, 51))
        self.event_id_num.setAutoFillBackground(True)
        self.event_id_num.setObjectName("event_id_num")
        self.datatimelabel = QtWidgets.QLabel(self.centralwidget)
        self.datatimelabel.setGeometry(QtCore.QRect(200, 620, 91, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.datatimelabel.setFont(font)
        self.datatimelabel.setAutoFillBackground(True)
        self.datatimelabel.setObjectName("datatimelabel")
        self.event_time_num = QtWidgets.QLCDNumber(self.centralwidget)
        self.event_time_num.setGeometry(QtCore.QRect(300, 610, 111, 51))
        self.event_time_num.setAutoFillBackground(True)
        self.event_time_num.setObjectName("event_time_num")
        self.dataindexlabel = QtWidgets.QLabel(self.centralwidget)
        self.dataindexlabel.setGeometry(QtCore.QRect(210, 560, 81, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dataindexlabel.setFont(font)
        self.dataindexlabel.setAutoFillBackground(True)
        self.dataindexlabel.setObjectName("dataindexlabel")
        self.MplWidget1 = MplWidget1(self.centralwidget)
        self.MplWidget1.setGeometry(QtCore.QRect(0, 110, 701, 441))
        self.MplWidget1.setObjectName("MplWidget1")
        self.MplWidget2 = MplWidget2(self.centralwidget)
        self.MplWidget2.setGeometry(QtCore.QRect(710, 110, 301, 241))
        self.MplWidget2.setObjectName("MplWidget2")
        self.coilcoordinateslabel = QtWidgets.QLabel(self.centralwidget)
        self.coilcoordinateslabel.setGeometry(QtCore.QRect(710, 70, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.coilcoordinateslabel.setFont(font)
        self.coilcoordinateslabel.setObjectName("coilcoordinateslabel")
        self.filename_label = QtWidgets.QLabel(self.centralwidget)
        self.filename_label.setGeometry(QtCore.QRect(320, 0, 91, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.filename_label.setFont(font)
        self.filename_label.setObjectName("filename_label")
        self.previous_button = QtWidgets.QPushButton(self.centralwidget)
        self.previous_button.setGeometry(QtCore.QRect(20, 570, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.previous_button.setFont(font)
        self.previous_button.setObjectName("previous_button")
        self.next_button = QtWidgets.QPushButton(self.centralwidget)
        self.next_button.setGeometry(QtCore.QRect(480, 570, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.next_button.setFont(font)
        self.next_button.setObjectName("next_button")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(250, 30, 311, 81))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.coil_coordinate_input = QtWidgets.QLineEdit(self.centralwidget)
        self.coil_coordinate_input.setGeometry(QtCore.QRect(870, 70, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.coil_coordinate_input.setFont(font)
        self.coil_coordinate_input.setObjectName("coil_coordinate_input")
        self.update_coil_button = QtWidgets.QPushButton(self.centralwidget)
        self.update_coil_button.setGeometry(QtCore.QRect(920, 70, 93, 28))
        self.update_coil_button.setObjectName("update_coil_button")
        self.reject_button = QtWidgets.QPushButton(self.centralwidget)
        self.reject_button.setGeometry(QtCore.QRect(50, 780, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.reject_button.setFont(font)
        self.reject_button.setObjectName("reject_button")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(710, 370, 411, 301))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.peaklatlabel = QtWidgets.QLabel(self.tab)
        self.peaklatlabel.setGeometry(QtCore.QRect(160, 14, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.peaklatlabel.setFont(font)
        self.peaklatlabel.setAutoFillBackground(True)
        self.peaklatlabel.setObjectName("peaklatlabel")
        self.troughlatlabel = QtWidgets.QLabel(self.tab)
        self.troughlatlabel.setGeometry(QtCore.QRect(160, 120, 112, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.troughlatlabel.setFont(font)
        self.troughlatlabel.setAutoFillBackground(True)
        self.troughlatlabel.setObjectName("troughlatlabel")
        self.troughvoltlabel = QtWidgets.QLabel(self.tab)
        self.troughvoltlabel.setGeometry(QtCore.QRect(10, 120, 130, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.troughvoltlabel.setFont(font)
        self.troughvoltlabel.setAutoFillBackground(True)
        self.troughvoltlabel.setObjectName("troughvoltlabel")
        self.peakvoltlabel = QtWidgets.QLabel(self.tab)
        self.peakvoltlabel.setGeometry(QtCore.QRect(10, 20, 120, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.peakvoltlabel.setFont(font)
        self.peakvoltlabel.setAutoFillBackground(True)
        self.peakvoltlabel.setObjectName("peakvoltlabel")
        self.peakmag_num = QtWidgets.QLineEdit(self.tab)
        self.peakmag_num.setGeometry(QtCore.QRect(10, 40, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.peakmag_num.setFont(font)
        self.peakmag_num.setObjectName("peakmag_num")
        self.peaklat_num = QtWidgets.QLineEdit(self.tab)
        self.peaklat_num.setGeometry(QtCore.QRect(160, 40, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.peaklat_num.setFont(font)
        self.peaklat_num.setObjectName("peaklat_num")
        self.troughmag_num = QtWidgets.QLineEdit(self.tab)
        self.troughmag_num.setGeometry(QtCore.QRect(10, 150, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.troughmag_num.setFont(font)
        self.troughmag_num.setObjectName("troughmag_num")
        self.troughlat_num = QtWidgets.QLineEdit(self.tab)
        self.troughlat_num.setGeometry(QtCore.QRect(160, 150, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.troughlat_num.setFont(font)
        self.troughlat_num.setObjectName("troughlat_num")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.zeroxinglabel = QtWidgets.QLabel(self.tab_2)
        self.zeroxinglabel.setGeometry(QtCore.QRect(10, 93, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.zeroxinglabel.setFont(font)
        self.zeroxinglabel.setAutoFillBackground(True)
        self.zeroxinglabel.setObjectName("zeroxinglabel")
        self.time_since_pulse_label_3 = QtWidgets.QLabel(self.tab_2)
        self.time_since_pulse_label_3.setGeometry(QtCore.QRect(210, 90, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.time_since_pulse_label_3.setFont(font)
        self.time_since_pulse_label_3.setAutoFillBackground(True)
        self.time_since_pulse_label_3.setObjectName("time_since_pulse_label_3")
        self.time_since_pulse_label_2 = QtWidgets.QLabel(self.tab_2)
        self.time_since_pulse_label_2.setGeometry(QtCore.QRect(210, 13, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.time_since_pulse_label_2.setFont(font)
        self.time_since_pulse_label_2.setAutoFillBackground(True)
        self.time_since_pulse_label_2.setObjectName("time_since_pulse_label_2")
        self.time_since_pulse_label = QtWidgets.QLabel(self.tab_2)
        self.time_since_pulse_label.setGeometry(QtCore.QRect(10, 170, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.time_since_pulse_label.setFont(font)
        self.time_since_pulse_label.setAutoFillBackground(True)
        self.time_since_pulse_label.setObjectName("time_since_pulse_label")
        self.stimintensitylabel = QtWidgets.QLabel(self.tab_2)
        self.stimintensitylabel.setGeometry(QtCore.QRect(10, 10, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.stimintensitylabel.setFont(font)
        self.stimintensitylabel.setAutoFillBackground(True)
        self.stimintensitylabel.setObjectName("stimintensitylabel")
        self.zcr_lat_num = QtWidgets.QLineEdit(self.tab_2)
        self.zcr_lat_num.setGeometry(QtCore.QRect(10, 110, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.zcr_lat_num.setFont(font)
        self.zcr_lat_num.setObjectName("zcr_lat_num")
        self.stimintensity_num = QtWidgets.QLineEdit(self.tab_2)
        self.stimintensity_num.setGeometry(QtCore.QRect(10, 30, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.stimintensity_num.setFont(font)
        self.stimintensity_num.setObjectName("stimintensity_num")
        self.onset_shift_num = QtWidgets.QLineEdit(self.tab_2)
        self.onset_shift_num.setGeometry(QtCore.QRect(210, 30, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.onset_shift_num.setFont(font)
        self.onset_shift_num.setObjectName("onset_shift_num")
        self.didt_num = QtWidgets.QLineEdit(self.tab_2)
        self.didt_num.setGeometry(QtCore.QRect(210, 110, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.didt_num.setFont(font)
        self.didt_num.setObjectName("didt_num")
        self.time_since_pulse_num = QtWidgets.QLineEdit(self.tab_2)
        self.time_since_pulse_num.setGeometry(QtCore.QRect(10, 190, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.time_since_pulse_num.setFont(font)
        self.time_since_pulse_num.setObjectName("time_since_pulse_num")
        self.tabWidget.addTab(self.tab_2, "")
        self.examiner = QtWidgets.QLabel(self.centralwidget)
        self.examiner.setGeometry(QtCore.QRect(110, 0, 191, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.examiner.setFont(font)
        self.examiner.setObjectName("examiner")
        self.filename = QtWidgets.QLabel(self.centralwidget)
        self.filename.setGeometry(QtCore.QRect(410, 0, 791, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.filename.setFont(font)
        self.filename.setObjectName("filename")
        self.readout_label = QtWidgets.QLabel(self.centralwidget)
        self.readout_label.setGeometry(QtCore.QRect(300, 750, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.readout_label.setFont(font)
        self.readout_label.setAutoFillBackground(True)
        self.readout_label.setObjectName("readout_label")
        self.channel_label = QtWidgets.QLabel(self.centralwidget)
        self.channel_label.setGeometry(QtCore.QRect(400, 692, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.channel_label.setFont(font)
        self.channel_label.setAutoFillBackground(True)
        self.channel_label.setObjectName("channel_label")
        self.readout = QtWidgets.QLabel(self.centralwidget)
        self.readout.setGeometry(QtCore.QRect(400, 750, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.readout.setFont(font)
        self.readout.setAutoFillBackground(True)
        self.readout.setObjectName("readout")
        self.muscle_label = QtWidgets.QLabel(self.centralwidget)
        self.muscle_label.setGeometry(QtCore.QRect(300, 692, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.muscle_label.setFont(font)
        self.muscle_label.setAutoFillBackground(True)
        self.muscle_label.setObjectName("muscle_label")
        self.update_attrs_button = QtWidgets.QPushButton(self.centralwidget)
        self.update_attrs_button.setGeometry(QtCore.QRect(710, 680, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.update_attrs_button.setFont(font)
        self.update_attrs_button.setObjectName("update_attrs_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1243, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.zeroxinglabel_2.setText(_translate("MainWindow", "comments:"))
        self.examinerlabel.setText(_translate("MainWindow", "Examiner: "))
        self.datatimelabel.setText(_translate("MainWindow", "time (ms):"))
        self.dataindexlabel.setText(_translate("MainWindow", "event ID:"))
        self.coilcoordinateslabel.setText(_translate("MainWindow", "Coil coordinates: "))
        self.filename_label.setText(_translate("MainWindow", "Filename: "))
        self.previous_button.setText(_translate("MainWindow", "Previous"))
        self.next_button.setText(_translate("MainWindow", "Next"))
        self.title.setText(_translate("MainWindow", "MEP Inspector"))
        self.coil_coordinate_input.setText(_translate("MainWindow", "0,0"))
        self.update_coil_button.setText(_translate("MainWindow", "Update Coil"))
        self.reject_button.setText(_translate("MainWindow", "Reject Trial"))
        self.peaklatlabel.setText(_translate("MainWindow", "peak latency (ms)"))
        self.troughlatlabel.setText(_translate("MainWindow", "trough latency (ms)"))
        self.troughvoltlabel.setText(_translate("MainWindow", "trough magnitude (uV)"))
        self.peakvoltlabel.setText(_translate("MainWindow", "peak magnitude (uV)"))
        self.peakmag_num.setText(_translate("MainWindow", "0"))
        self.peaklat_num.setText(_translate("MainWindow", "0"))
        self.troughmag_num.setText(_translate("MainWindow", "0"))
        self.troughlat_num.setText(_translate("MainWindow", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Mag/Lat"))
        self.zeroxinglabel.setText(_translate("MainWindow", "zero crossing latency (ms)"))
        self.time_since_pulse_label_3.setText(_translate("MainWindow", "di/dt"))
        self.time_since_pulse_label_2.setText(_translate("MainWindow", "onset shift (ms)"))
        self.time_since_pulse_label.setText(_translate("MainWindow", "time since last pulse (ms)"))
        self.stimintensitylabel.setText(_translate("MainWindow", "stim intensity (% MSO)"))
        self.zcr_lat_num.setText(_translate("MainWindow", "0"))
        self.stimintensity_num.setText(_translate("MainWindow", "0"))
        self.onset_shift_num.setText(_translate("MainWindow", "0"))
        self.didt_num.setText(_translate("MainWindow", "0"))
        self.time_since_pulse_num.setText(_translate("MainWindow", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Other"))
        self.examiner.setText(_translate("MainWindow", "HiWi"))
        self.filename.setText(_translate("MainWindow", "Filename"))
        self.readout_label.setText(_translate("MainWindow", "Readout:"))
        self.channel_label.setText(_translate("MainWindow", "EDC_R"))
        self.readout.setText(_translate("MainWindow", "Contralateral MEP"))
        self.muscle_label.setText(_translate("MainWindow", "Muscle:"))
        self.update_attrs_button.setText(_translate("MainWindow", "Update Attributes"))
from offspect.gui.mplwidget import MplWidget1, MplWidget2
