# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'visual_inspection_gui.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1743, 1079)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.troughlatency = QtWidgets.QLCDNumber(self.centralwidget)
        self.troughlatency.setGeometry(QtCore.QRect(690, 863, 64, 20))
        self.troughlatency.setAutoFillBackground(True)
        self.troughlatency.setObjectName("troughlatency")
        self.zeroxinglabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.zeroxinglabel_2.setGeometry(QtCore.QRect(1200, 730, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.zeroxinglabel_2.setFont(font)
        self.zeroxinglabel_2.setAutoFillBackground(True)
        self.zeroxinglabel_2.setObjectName("zeroxinglabel_2")
        self.peakvolts = QtWidgets.QLCDNumber(self.centralwidget)
        self.peakvolts.setGeometry(QtCore.QRect(540, 810, 64, 23))
        self.peakvolts.setAutoFillBackground(True)
        self.peakvolts.setObjectName("peakvolts")
        self.troughlatlabel = QtWidgets.QLabel(self.centralwidget)
        self.troughlatlabel.setGeometry(QtCore.QRect(690, 840, 112, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.troughlatlabel.setFont(font)
        self.troughlatlabel.setAutoFillBackground(True)
        self.troughlatlabel.setObjectName("troughlatlabel")
        self.peaklatlabel = QtWidgets.QLabel(self.centralwidget)
        self.peaklatlabel.setGeometry(QtCore.QRect(690, 780, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.peaklatlabel.setFont(font)
        self.peaklatlabel.setAutoFillBackground(True)
        self.peaklatlabel.setObjectName("peaklatlabel")
        self.peaklatency = QtWidgets.QLCDNumber(self.centralwidget)
        self.peaklatency.setGeometry(QtCore.QRect(690, 810, 64, 23))
        self.peaklatency.setAutoFillBackground(True)
        self.peaklatency.setObjectName("peaklatency")
        self.troughvoltlabel = QtWidgets.QLabel(self.centralwidget)
        self.troughvoltlabel.setGeometry(QtCore.QRect(540, 840, 130, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.troughvoltlabel.setFont(font)
        self.troughvoltlabel.setAutoFillBackground(True)
        self.troughvoltlabel.setObjectName("troughvoltlabel")
        self.peakvoltlabel = QtWidgets.QLabel(self.centralwidget)
        self.peakvoltlabel.setGeometry(QtCore.QRect(540, 786, 120, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.peakvoltlabel.setFont(font)
        self.peakvoltlabel.setAutoFillBackground(True)
        self.peakvoltlabel.setObjectName("peakvoltlabel")
        self.stimintensitylabel = QtWidgets.QLabel(self.centralwidget)
        self.stimintensitylabel.setGeometry(QtCore.QRect(30, 790, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.stimintensitylabel.setFont(font)
        self.stimintensitylabel.setAutoFillBackground(True)
        self.stimintensitylabel.setObjectName("stimintensitylabel")
        self.commentbox = QtWidgets.QTextEdit(self.centralwidget)
        self.commentbox.setGeometry(QtCore.QRect(1200, 750, 301, 192))
        self.commentbox.setObjectName("commentbox")
        self.examinerlabel = QtWidgets.QLabel(self.centralwidget)
        self.examinerlabel.setGeometry(QtCore.QRect(10, 0, 101, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.examinerlabel.setFont(font)
        self.examinerlabel.setObjectName("examinerlabel")
        self.datatime = QtWidgets.QLCDNumber(self.centralwidget)
        self.datatime.setGeometry(QtCore.QRect(410, 730, 64, 23))
        self.datatime.setAutoFillBackground(True)
        self.datatime.setObjectName("datatime")
        self.datatimelabel = QtWidgets.QLabel(self.centralwidget)
        self.datatimelabel.setGeometry(QtCore.QRect(300, 730, 101, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.datatimelabel.setFont(font)
        self.datatimelabel.setAutoFillBackground(True)
        self.datatimelabel.setObjectName("datatimelabel")
        self.dataindex = QtWidgets.QLCDNumber(self.centralwidget)
        self.dataindex.setGeometry(QtCore.QRect(410, 700, 64, 23))
        self.dataindex.setAutoFillBackground(True)
        self.dataindex.setObjectName("dataindex")
        self.dataindexlabel = QtWidgets.QLabel(self.centralwidget)
        self.dataindexlabel.setGeometry(QtCore.QRect(310, 700, 91, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.dataindexlabel.setFont(font)
        self.dataindexlabel.setAutoFillBackground(True)
        self.dataindexlabel.setObjectName("dataindexlabel")
        self.zeroxinglat = QtWidgets.QLCDNumber(self.centralwidget)
        self.zeroxinglat.setGeometry(QtCore.QRect(30, 860, 64, 23))
        self.zeroxinglat.setAutoFillBackground(True)
        self.zeroxinglat.setObjectName("zeroxinglat")
        self.zeroxinglabel = QtWidgets.QLabel(self.centralwidget)
        self.zeroxinglabel.setGeometry(QtCore.QRect(30, 843, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.zeroxinglabel.setFont(font)
        self.zeroxinglabel.setAutoFillBackground(True)
        self.zeroxinglabel.setObjectName("zeroxinglabel")
        self.stimintensity = QtWidgets.QLCDNumber(self.centralwidget)
        self.stimintensity.setGeometry(QtCore.QRect(30, 810, 64, 23))
        self.stimintensity.setAutoFillBackground(True)
        self.stimintensity.setObjectName("stimintensity")
        self.troughvolts = QtWidgets.QLCDNumber(self.centralwidget)
        self.troughvolts.setGeometry(QtCore.QRect(540, 860, 64, 23))
        self.troughvolts.setAutoFillBackground(True)
        self.troughvolts.setObjectName("troughvolts")
        self.MplWidget1 = MplWidget1(self.centralwidget)
        self.MplWidget1.setGeometry(QtCore.QRect(0, 100, 1141, 581))
        self.MplWidget1.setObjectName("MplWidget1")
        self.MplWidget2 = MplWidget2(self.centralwidget)
        self.MplWidget2.setGeometry(QtCore.QRect(1140, 60, 591, 511))
        self.MplWidget2.setObjectName("MplWidget2")
        self.coilcoordinateslabel = QtWidgets.QLabel(self.centralwidget)
        self.coilcoordinateslabel.setGeometry(QtCore.QRect(1160, 30, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.coilcoordinateslabel.setFont(font)
        self.coilcoordinateslabel.setObjectName("coilcoordinateslabel")
        self.filename = QtWidgets.QLabel(self.centralwidget)
        self.filename.setGeometry(QtCore.QRect(10, 30, 91, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.filename.setFont(font)
        self.filename.setObjectName("filename")
        self.previous_button = QtWidgets.QPushButton(self.centralwidget)
        self.previous_button.setGeometry(QtCore.QRect(30, 690, 161, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.previous_button.setFont(font)
        self.previous_button.setObjectName("previous_button")
        self.next_button = QtWidgets.QPushButton(self.centralwidget)
        self.next_button.setGeometry(QtCore.QRect(590, 690, 161, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.next_button.setFont(font)
        self.next_button.setObjectName("next_button")
        self.time_since_pulse_label = QtWidgets.QLabel(self.centralwidget)
        self.time_since_pulse_label.setGeometry(QtCore.QRect(30, 890, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.time_since_pulse_label.setFont(font)
        self.time_since_pulse_label.setAutoFillBackground(True)
        self.time_since_pulse_label.setObjectName("time_since_pulse_label")
        self.time_since_pulse = QtWidgets.QLCDNumber(self.centralwidget)
        self.time_since_pulse.setGeometry(QtCore.QRect(30, 910, 64, 23))
        self.time_since_pulse.setAutoFillBackground(True)
        self.time_since_pulse.setObjectName("time_since_pulse")
        self.time_since_pulse_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.time_since_pulse_label_2.setGeometry(QtCore.QRect(230, 793, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.time_since_pulse_label_2.setFont(font)
        self.time_since_pulse_label_2.setAutoFillBackground(True)
        self.time_since_pulse_label_2.setObjectName("time_since_pulse_label_2")
        self.time_since_pulse_2 = QtWidgets.QLCDNumber(self.centralwidget)
        self.time_since_pulse_2.setGeometry(QtCore.QRect(230, 810, 64, 23))
        self.time_since_pulse_2.setAutoFillBackground(True)
        self.time_since_pulse_2.setObjectName("time_since_pulse_2")
        self.time_since_pulse_label_3 = QtWidgets.QLabel(self.centralwidget)
        self.time_since_pulse_label_3.setGeometry(QtCore.QRect(230, 843, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.time_since_pulse_label_3.setFont(font)
        self.time_since_pulse_label_3.setAutoFillBackground(True)
        self.time_since_pulse_label_3.setObjectName("time_since_pulse_label_3")
        self.time_since_pulse_3 = QtWidgets.QLCDNumber(self.centralwidget)
        self.time_since_pulse_3.setGeometry(QtCore.QRect(230, 860, 64, 23))
        self.time_since_pulse_3.setAutoFillBackground(True)
        self.time_since_pulse_3.setObjectName("time_since_pulse_3")
        self.muscle_label = QtWidgets.QLabel(self.centralwidget)
        self.muscle_label.setGeometry(QtCore.QRect(20, 70, 81, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.muscle_label.setFont(font)
        self.muscle_label.setAutoFillBackground(True)
        self.muscle_label.setObjectName("muscle_label")
        self.muscle_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.muscle_label_2.setGeometry(QtCore.QRect(100, 70, 81, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.muscle_label_2.setFont(font)
        self.muscle_label_2.setAutoFillBackground(True)
        self.muscle_label_2.setObjectName("muscle_label_2")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(480, 20, 311, 81))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.coil_coordinate_input = QtWidgets.QLineEdit(self.centralwidget)
        self.coil_coordinate_input.setGeometry(QtCore.QRect(1360, 30, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.coil_coordinate_input.setFont(font)
        self.coil_coordinate_input.setObjectName("coil_coordinate_input")
        self.update_coil_button = QtWidgets.QPushButton(self.centralwidget)
        self.update_coil_button.setGeometry(QtCore.QRect(1410, 30, 93, 28))
        self.update_coil_button.setObjectName("update_coil_button")
        self.reject_button = QtWidgets.QPushButton(self.centralwidget)
        self.reject_button.setGeometry(QtCore.QRect(1530, 800, 201, 121))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.reject_button.setFont(font)
        self.reject_button.setObjectName("reject_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1743, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.zeroxinglabel_2.setText(_translate("MainWindow", "comments:"))
        self.troughlatlabel.setText(_translate("MainWindow", "trough latency (ms)"))
        self.peaklatlabel.setText(_translate("MainWindow", "peak latency (ms)"))
        self.troughvoltlabel.setText(_translate("MainWindow", "trough magnitude (uV)"))
        self.peakvoltlabel.setText(_translate("MainWindow", "peak magnitude (uV)"))
        self.stimintensitylabel.setText(_translate("MainWindow", "stim intensity (% MSO)"))
        self.examinerlabel.setText(_translate("MainWindow", "Examiner: "))
        self.datatimelabel.setText(_translate("MainWindow", "time (ms):"))
        self.dataindexlabel.setText(_translate("MainWindow", "event ID:"))
        self.zeroxinglabel.setText(_translate("MainWindow", "zero crossing latency (ms)"))
        self.coilcoordinateslabel.setText(_translate("MainWindow", "TMS coil coordinates: "))
        self.filename.setText(_translate("MainWindow", "Filename: "))
        self.previous_button.setText(_translate("MainWindow", "Previous"))
        self.next_button.setText(_translate("MainWindow", "Next"))
        self.time_since_pulse_label.setText(_translate("MainWindow", "time since last pulse (ms)"))
        self.time_since_pulse_label_2.setText(_translate("MainWindow", "onset shift (ms)"))
        self.time_since_pulse_label_3.setText(_translate("MainWindow", "di/dt"))
        self.muscle_label.setText(_translate("MainWindow", "Muscle:"))
        self.muscle_label_2.setText(_translate("MainWindow", "EDC_R"))
        self.title.setText(_translate("MainWindow", "MEP Inspector"))
        self.coil_coordinate_input.setText(_translate("MainWindow", "0,0"))
        self.update_coil_button.setText(_translate("MainWindow", "Update Coil"))
        self.reject_button.setText(_translate("MainWindow", "Reject Trial"))
from offspect.gui.mplwidget import MplWidget1, MplWidget2
